export interface Product {
  id: string
  name: string
  category: string
  subcategory: string
  type?: string
  image: string
  price: number
  originalPrice?: number
  discount?: number
  isFeatured?: boolean
  sizes?: string[]
}

export const products: Product[] = [
  // Times Europeus
  {
    id: "1",
    name: "Camisão Real Madrid (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "REAL MADRID",
    type: "CASA",
    image: "/Camiseta_Real_Madrid_Premium.webp",
    price: 199.9,
    originalPrice: 250.0,
    discount: 20,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "2",
    name: "Camiseta AC Milan (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "AC MILAN",
    type: "FORA",
    image: "/Camiseta_AC_Milan_Premium_Cinza.webp",
    price: 130.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "3",
    name: "Camiseta Ajax Edição Limitada (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "AJAX",
    type: "ESPECIAL",
    image: "/Camiseta_Ajax_Edicao_Limitada_Premium.webp",
    price: 130.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "4",
    name: "Camiseta Barcelona (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "BARCELONA",
    type: "TERCEIRA",
    image: "/Camiseta_Barcelona_Premium_Preta.webp",
    price: 130.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "5",
    name: "Camiseta Celtic (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "CELTIC",
    type: "CASA",
    image: "/Camiseta_Celtic_Premium.webp",
    price: 130.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "6",
    name: "Camiseta Liverpool (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "LIVERPOOL",
    type: "CASA",
    image: "/Camiseta_Liverpool_Premium.webp",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "7",
    name: "Camiseta Manchester City (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "MANCHESTER CITY",
    type: "CASA",
    image: "/Camiseta_Manchester_City_Premium_Roxa.webp",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "8",
    name: "Camiseta PSG (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "PSG",
    type: "CASA",
    image: "/Camiseta_PSG_Edicao_Limitada_Premium.webp",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "9",
    name: "Camiseta Bayern München (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "BAYERN",
    type: "CASA",
    image: "/Camiseta_Bayern_Munchen_Premium_Vermelha.webp",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "10",
    name: "Camiseta Juventus (Premium)",
    category: "TIMES EUROPEUS",
    subcategory: "JUVENTUS",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  // Times Brasileiros
  {
    id: "11",
    name: "Camisão Flamengo (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "FLAMENGO",
    type: "CASA",
    image: "/placeholder.svg",
    price: 199.9,
    originalPrice: 250.0,
    discount: 20,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "12",
    name: "Camiseta Flamengo (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "FLAMENGO",
    type: "FORA",
    image: "/placeholder.svg",
    price: 130.0,
    originalPrice: 160.0,
    discount: 19,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "13",
    name: "Camiseta Corinthians (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "CORINTHIANS",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "14",
    name: "Camiseta Palmeiras (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "PALMEIRAS",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "15",
    name: "Camiseta São Paulo (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "SÃO PAULO",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "16",
    name: "Camiseta Santos (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "SANTOS",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "17",
    name: "Camiseta Grêmio (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "GRÊMIO",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "18",
    name: "Camiseta Internacional (Premium)",
    category: "TIMES BRASILEIROS",
    subcategory: "INTERNACIONAL",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  // Seleções
  {
    id: "19",
    name: "Camiseta Argentina (Premium)",
    category: "SELEÇÕES",
    subcategory: "ARGENTINA",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "20",
    name: "Camiseta Japão 2022 (Premium)",
    category: "SELEÇÕES",
    subcategory: "JAPÃO",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "21",
    name: "Camiseta Portugal (Premium)",
    category: "SELEÇÕES",
    subcategory: "PORTUGAL",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "22",
    name: "Camiseta Brasil (Premium)",
    category: "SELEÇÕES",
    subcategory: "BRASIL",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "23",
    name: "Camiseta Alemanha (Premium)",
    category: "SELEÇÕES",
    subcategory: "ALEMANHA",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "24",
    name: "Camiseta França (Premium)",
    category: "SELEÇÕES",
    subcategory: "FRANÇA",
    type: "CASA",
    image: "/placeholder.svg",
    price: 130.0,
    sizes: ["P", "M", "G", "GG"],
  },
  // Outros Continentes
  {
    id: "25",
    name: "Camiseta Al-Hilal (Premium)",
    category: "OUTROS CONTINENTES",
    subcategory: "AL-HILAL",
    type: "CASA",
    image: "/placeholder.svg",
    price: 150.0,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "26",
    name: "Camiseta Al-Nassr (Premium)",
    category: "OUTROS CONTINENTES",
    subcategory: "AL-NASSR",
    type: "CASA",
    image: "/placeholder.svg",
    price: 150.0,
    sizes: ["P", "M", "G", "GG"],
  },
  // Retrôs
  {
    id: "27",
    name: "Camiseta Brasil Retrô 2002 (Premium)",
    category: "RETRÔS",
    subcategory: "BRASIL",
    type: "RETRÔ",
    image: "/placeholder.svg",
    price: 140.0,
    isFeatured: true,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "28",
    name: "Camiseta Argentina Retrô 1986 (Premium)",
    category: "RETRÔS",
    subcategory: "ARGENTINA",
    type: "RETRÔ",
    image: "/placeholder.svg",
    price: 140.0,
    sizes: ["P", "M", "G", "GG"],
  },
]

export const categories = [
  { id: "all", name: "Todos", count: products.length },
  {
    id: "times-europeus",
    name: "Times Europeus",
    count: products.filter((p) => p.category === "TIMES EUROPEUS").length,
  },
  {
    id: "times-brasileiros",
    name: "Times Brasileiros",
    count: products.filter((p) => p.category === "TIMES BRASILEIROS").length,
  },
  { id: "selecoes", name: "Seleções", count: products.filter((p) => p.category === "SELEÇÕES").length },
  {
    id: "outros-continentes",
    name: "Outros Continentes",
    count: products.filter((p) => p.category === "OUTROS CONTINENTES").length,
  },
  { id: "retros", name: "Retrôs", count: products.filter((p) => p.category === "RETRÔS").length },
]

export const priceRanges = [
  { id: "all", name: "Todos os preços", min: 0, max: Number.POSITIVE_INFINITY },
  { id: "under-130", name: "Até R$ 130", min: 0, max: 130 },
  { id: "130-150", name: "R$ 130 - R$ 150", min: 130, max: 150 },
  { id: "150-200", name: "R$ 150 - R$ 200", min: 150, max: 200 },
  { id: "over-200", name: "Acima de R$ 200", min: 200, max: Number.POSITIVE_INFINITY },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}
